id = "github"
kind = "integration"
driver = "github"
enabled = true

[policy]
trusted_users = [
  "SigureMo",
  "risemeup1",
  "swgu98",
  "huangjiyi",
  "zyfncg",
  "gouzil",
  "sunzhongkai588",
  "DrRyanHuang",
  "omoYang",
  "zrr1999",
]
